apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: ${{values.description}}
  tags:
    - java
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.destination.repo | dump}}
    keptn.sh/service: ${{values.component_id | dump}}
    keptn.sh/project: ${{values.component_id | dump}}
    sonarqube.org/project-key: ${{values.destination.owner + "_" + values.destination.repo}}
    prometheus.io/rule: "container_cpu_usage_seconds_total{namespace='${{values.component_id | dump}}'}"
    prometheus.io/alert: "Excessive Memory Usage"
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
