apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}-frontend
        image: {{ include "keptn-image-name" . }}-frontend:{{ include "keptn-image-tag" . }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP

